Extending the select component to support filtering
squirro/materialize pull request #4
Opened 2018-05-04 14:24 UTC by andresenra

![image](https://user-images.githubusercontent.com/30179738/39633196-95127182-4fb7-11e8-86e6-7d1494838328.png)

2018-05-04 14:53 UTC, Fasani approved these changes

2018-05-15 13:40 UTC, Fasani commented
@andresenra this has a conflict now.

2018-05-15 13:41 UTC, Fasani commented
@andresenra also it seems a rather larger number of lines being removed? Any idea?

2018-05-15 14:46 UTC, WiktorStarczewski commented
I like it, quite invasive though so might not survive a 1.0 update - we'll need to implement it again there.
(1.0 is in rc1 now and progressing)

2018-05-15 14:48 UTC, WiktorStarczewski requested changes

2018-05-15 14:48 UTC, WiktorStarczewski commented on js/forms.js
> +          var element = $('<span><input type="text" class="search" style="margin: 5px 0px 16px 15px; width: 96%;" placeholder="' + placeholder + '"></span>');
Why inline style and not a class?

2018-06-13 19:22 UTC, Fasani commented
Fixed scroll bug. Added support for max number of selected items.

https://www.useloom.com/share/66995ef79f8741c3a04d93e868654265

2018-06-13 19:23 UTC, Fasani commented
@WiktorStarczewski and @andresenra please review and see video

2018-06-14 07:46 UTC, WiktorStarczewski approved these changes

2018-06-14 08:12 UTC, merged